### ISSUE TITLE
Failed to install with python 3.12

### ISSUE THREAD

**Issue by Finenyaco** [gpustack/vox-box#1]
**Steps to reproduce**

Run `pip install vox-box`

```
...
Requirement already satisfied: pipx<2.0.0,>=1.7.1 in /home/seal/anaconda3/envs/py312/lib/python3.12/site-packages (from vox-box) (1.7.1)
Collecting pyarrow<19.0.0,>=18.0.0 (from vox-box)
  Using cached pyarrow-18.1.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.3 kB)
Collecting pynini==2.1.5 (from vox-box)
  Using cached pynini-2.1.5.tar.gz (627 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-99t3ugyu/pynini_81441cdb29cf4ac79c019b0db9e4c465/setup.py", line 22, in <module>
          from Cython.Build import cythonize
      ModuleNotFoundError: No module named 'Cython'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Environment:**
```
➜ python -V
Python 3.12.7
```

**Comment by pengjiang80** [comment]
I tried and failed at grpc-tools

Refer to https://github.com/google/bumble/issues/459, can we upgrade to new version of grpc-tools and not stick on 1.57?

**Comment by aiwantaozi** [comment]
0.0.4 should fixed, please try to install the latest in Linux.

**Comment by Finenyaco** [comment]
Verified on vox-box 0.0.4
